config/routes.rb
Rails.application.routes.draw do
  root to: "users#show"

  get "/login"    => "pages#home"

  resources :friends

  post "/new_friend" => "friends#custom_create"

  resource :user, :only => [:show, :edit, :update] do
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
end

app/models/friend.rb
class Friend < ActiveRecord::Base
  belongs_to :user

  validates :user, :birthday, :presence => true

  def show_birthday
    birthday.strftime("%B ") + birthday.day.ordinalize
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :friends

  devise :database_authenticatable, :recoverable, :rememberable,
    # :confirmable,
    :omniauthable, :omniauth_providers => [:facebook]

  def self.send_reminders
    all.each{ |u| u.send_reminders_if_any }
  end

  def send_reminders_if_any
    if week_ofs.present? || day_ofs.present?
      UserMailer.birthday(self, week_ofs, day_ofs).deliver
    end
  end

  def week_ofs
    if one_week
      friends_with_birthdays_on(7.days.from_now)
    end
  end

  def day_ofs
    if day_of
      friends_with_birthdays_on(Date.today)
    end
  end

  def fb_friend(id)
    fb_friends.select{|a| a.raw_attributes["id"] == id.to_s}.first.try(:fetch)
  end

  def new_fb_friends
    fb_friends.reject{|f| f.id.in? friends.pluck(:facebook_id) }
  end

  def fb_friends
    @fb_friends ||= fb_user.friends
  end

  def fb_user
    @fb_user ||= FbGraph::User.me(token).fetch
  end

  private

  def friends_with_birthdays_on(target)
    friends.select do |friend|
      friend.birthday.month == target.month && friend.birthday.day == target.day
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def require_logged_in
    redirect_to '/login' unless current_user
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :authenticate_user!

  def new
  end

  def custom_create
    current_user.friends.create(params[:friend].permit!)
    redirect_to current_user, :notice => "Friend added!"
  end

  def create
    params["new_friends"]["friends"].reject(&:blank?).each do |friend_id|
      fb_friend = current_user.fb_friend(friend_id)
      current_user.friends.where(:facebook_id => fb_friend.id).first_or_create do |user|
        user.name          = fb_friend.name
        user.birthday      = fb_friend.birthday.try(:change, :year => 2000)
        user.facebook_link = fb_friend.link
        user.image         = fb_friend.picture
      end
    end

    redirect_to "/user"
  end

  def destroy
    friend = Friend.find(params[:id])
    friend.destroy

    redirect_to :back, :notice => "#{friend.name} removed from your list."
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.where(omniauth_hash.slice(:provider, :uid)).first_or_create(credentials)

    if @user.persisted?
      @user.update_attributes(credentials.slice(:token))
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  private

  def omniauth_hash
    request.env["omniauth.auth"]
  end

  def credentials
    {
      :provider => omniauth_hash.provider,
      :uid      => omniauth_hash.uid,
      :email    => omniauth_hash.info.email,
      :token    => omniauth_hash.credentials.token,
      :password => Devise.friendly_token[0,20],
      :name     => omniauth_hash.info.name,
      :image    => omniauth_hash.info.image
    }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_logged_in

  def show
    @friends = sorted_friends
  end

  def edit
  end

  def update
    current_user.update_attributes(params[:user].permit!)
    redirect_to root_url, :notice => "Preferences updated."
  end

  private

  def sorted_friends
    if sort_column == 'birthday'
      current_user.friends.order(:birthday)
    else
      current_user.friends.sort_by{|p| p.name.split(" ").last}
    end
  end

  def sort_column
    params[:sort].presence || 'name'
  end
  helper_method :sort_column

end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column)
    title ||= column.titleize
    css_class = column == sort_column ? "current" : nil
    link_to title, {:sort => column}, {:class => css_class}
  end
end

app/views/friends/new.html.erb
<h1>New Friend!</h1>

<%= simple_form_for :friend, :url => "/new_friend" do |f| %>
  <%= f.input :name %>
  <%= f.input :birthday %>

  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Birthdays</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

 <% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "alert alert-#{key}") %>
<% end %>

 <%= yield %>

<%= javascript_include_tag 'application' %>

</body>
</html>

app/views/pages/home.html.erb
<%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>

app/views/users/edit.html.erb
<h3>Preferences</h3>

<%= simple_form_for current_user do |f| %>
  <%= f.input :email %>
  <%= f.input :one_week, :label => "One Week Notice" %>
  <%= f.input :day_of, :label => "Day Of Notice" %>

  <br>

  <%= f.submit %>
  <%= link_to "Back", root_url %>
<% end %>

app/views/users/show.html.erb
<%= link_to "Preferences", edit_user_path %>

<br><br>

<%= simple_form_for :new_friends, :url => friends_path do |f| %>
  <%= f.input :friends,
    :as         => :select,
    :collection => current_user.new_fb_friends.map{|f| [f.name, f.raw_attributes["id"]]},
    :input_html => { :multiple => true }
  %>

  <%= f.submit "Add friends" %>
<% end %>

<%= link_to "Add custom friend", new_friend_path %>

<h2>Friends</h2>
<table style="width:400px">
  <tr>
    <td></td>
    <td><%= sortable("name") %></td>
    <td><%= sortable("birthday") %></td>
    <td></td>
  </tr>
  <% @friends.each do |friend| %>
    <tr>
      <td><%= image_tag friend.image %></td>
      <td><%= link_to friend.name, friend.facebook_link %></td>
      <td><%= friend.show_birthday %></td>
      <td><%= link_to "x", friend, :method => :delete, :data => {:confirm => "Are you sure?"} %></td>
    </tr>
  <% end %>
</table>